[package]
name = "hellorust"
version = "1.0.0"
edition = "2021"
authors = ["Ali Sajid Imami"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }