[package]
name = "hellorltk"
version = "1.4.0"
edition = "2021"
authors = ["Ali Sajid Imami"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
specs = "0.18.0"
specs-derive = "0.4.1"
